### ISSUE TITLE
配置了Typecho后发布失败问题

### ISSUE THREAD

**Issue by pengcheng820** [terwer/sy-post-publisher#122]
配置了Typecho后发布失败问题

![image](https://github.com/terwer/sy-post-publisher/assets/12994898/706cab4c-31e5-4a5c-9802-0bb134b24832)

![image](https://github.com/terwer/sy-post-publisher/assets/12994898/93fad3d2-c343-4804-bed5-f751a390d9b3)

![image](https://github.com/terwer/sy-post-publisher/assets/12994898/dc80d07e-f1f2-4057-aabd-c0077cca9a19)

**Comment by terwer** [comment]
昨天最新版的问题，已经修复，需要升级到1.5.2。等下下午更新下吧，已经提交了。1.5.2已经修复。
插件版 1.5.2+
