### ISSUE TITLE
使用问题，版本规划集中反馈贴

### ISSUE THREAD

**Issue by terwer** [terwer/sy-post-publisher#2]
大家有什么【需求建议】【使用心得】，欢迎回帖哦~

**Comment by terwer** [comment]
v0.0.3 版本规划

https://github.com/users/terwer/projects/1/views/1

**Comment by lentikr** [comment]
我现在主要尝试了博客园和语雀。现阶段的使用有几个问题：
- 一键生成属性这个功能好像无法取消勾选？我其实不太喜欢自动提取的标签，每次都需要发布后再去相关平台删掉。
- 博客园默认每次发布到随笔，不知道能否设置发布到文章？
- 语雀发布能否设置知识库和路径？
- [bug]语雀发布后自己手动删除语雀中对应的文档，随后在本插件中点击更新或取消发布都会报错

**Comment by terwer** [comment]
> 我现在主要尝试了博客园和语雀。现阶段的使用有几个问题：
> 
> * 一键生成属性这个功能好像无法取消勾选？我其实不太喜欢自动提取的标签，每次都需要发布后再去相关平台删掉。
> * 博客园默认每次发布到随笔，不知道能否设置发布到文章？
> * 语雀发布能否设置知识库和路径？
> * [bug]语雀发布后自己手动删除语雀中对应的文档，随后在本插件中点击更新或取消发布都会报错

感谢反馈，我针对性回答下。

1、一键操作，后续设置一个全局开关，用户可自行关闭。PS：当时设置这个主要是为懒人准备，下版本将提供关闭选项。
请关注：https://github.com/terwer/src-sy-post-publisher/issues/60

2、博客园没有提供发布到问文章的选项，抱歉。但是下版本会加入分类选择功能
https://github.com/terwer/src-sy-post-publisher/issues/56

3、语雀发布能否设置知识库和路径这个0.0.3版本会完整支持，请关注
https://github.com/terwer/src-sy-post-publisher/issues/56

4、删除或者更新检测会加上
https://github.com/terwer/src-sy-post-publisher/issues/61

感谢反馈。
