### ISSUE TITLE
云床配置不生效

### ISSUE THREAD

**Issue by xiaomudk** [terwer/sy-post-publisher#3]
@terwer 您好， 我在`SiYuan/data/widgets/sy-post-publisher/lib/picgo/picgo.cfg.json`文件里添加了图床配置，但是上传图片报错，查看`picgo.cfg.json`被恢复成默认配置了。

```
cat picgo.cfg.json
{
  "picBed": {
    "uploader": "smms",
    "current": "smms"
  },
  "picgoPlugins": {}
}
```

操作系统: macOs
思源版本：v2.63
sy-post-publisher版本: 0.68

**Comment by terwer** [comment]
我本地验证一下看看。
另外， 0.7.0 正在重新开发PicGO 图形化配置界面，请关注进度 https://github.com/terwer/src-sy-post-publisher/issues/319

**Comment by terwer** [comment]
@xiaomudk 请使用 `0.7.0-beta1` 图形界面配置试试。

[sy-post-publisher-widget-0.7.0-beta1.zip](https://github.com/terwer/sy-post-publisher/files/10684865/sy-post-publisher-widget-0.7.0-beta1.zip)

**Comment by xiaomudk** [comment]
@terwer 非常感谢，我测试了下，配置是生效了，但是上传图片报了401
```
"statusCode":401,"message":"Request failed with status code 401","stack":{},"response":{"status":401,"statusCode":401,"body":{"msg":"need date header","code":40100001,"id":"1f08f0f9fd51f34643a306fdf8d7d87a"}}}
```

同样的配置(使用的又拍云)直接使用picgo上传是没有问题的

**Comment by terwer** [comment]
@xiaomudk Eletron的安全机制拦截了date字段导致。

![image](https://user-images.githubusercontent.com/3259282/217827355-3dc6215e-fb95-4220-860a-e9b4c5568c38.png)

由于我目前自用的只用Github，其他平台没有严格测试。稍后我会对所有平台重新进行验证。
`upyun` 的问题已修复，请使用下面最新beta版本验证。

[sy-post-publisher-widget-0.7.0-beta3.zip](https://github.com/terwer/sy-post-publisher/files/10699315/sy-post-publisher-widget-0.7.0-beta3.zip)

**Comment by xiaomudk** [comment]
@terwer  辛苦辛苦
我使用beta3，又出现了另外一个报错
```
操作失败=>Error: upload error, please check you picgo config!Detail info:{"code":"ERR_INVALID_ARG_TYPE"}
```

**Comment by terwer** [comment]
@xiaomudk 大佬，上面回复了，最近有空提供点配置信息吗，还有操作步骤？

**Comment by xiaomudk** [comment]
@terwer 我的操作步骤：
![image](https://user-images.githubusercontent.com/3413361/218251430-d1059819-d99f-4916-b0fc-382565d5a01a.png)
![image](https://user-images.githubusercontent.com/3413361/218251508-cb8d1eb7-99bf-4a83-ae6c-149db150cb8d.png)
![image](https://user-images.githubusercontent.com/3413361/218251566-046aa880-9cb1-470c-917d-d12efc27cf62.png)

如果需要，咱们可以微信沟通下: xiaomudk-wx

**Comment by terwer** [comment]
已修复，请使用 beta-5 验证。
[sy-post-publisher-widget-0.7.0-beta5.zip](https://github.com/terwer/sy-post-publisher/files/10713877/sy-post-publisher-widget-0.7.0-beta5.zip)
