### ISSUE TITLE
图床相关反馈

### ISSUE THREAD

**Issue by OpaqueGlass** [terwer/sy-post-publisher#5]
使用图床功能时遇到了一些问题，来反馈一下：

1. 浏览器扩展：
如果图片包含标题，获取到的图片链接包括图片标题，因而无法上传到图床（下图是picgo日志）
![image](https://user-images.githubusercontent.com/52985952/223913192-077aac33-0049-4efa-a7e0-beb10d6091f9.png)

2. 挂件 v0.7.2：

思源v2.7.8，上传时似乎无法获取到data路径
![image](https://user-images.githubusercontent.com/52985952/223913397-e2a73c6a-9ffd-4f46-9457-4c3f7eee30d6.png)

window.terwer似乎不存在
![image](https://user-images.githubusercontent.com/52985952/223913641-486de90f-23d8-4225-91a7-3f4805bcbc44.png)

（不太明白为什么手动加上window.terwer.dataDir也不行）

**Comment by terwer** [comment]
问题1会安排修复
问题2 =，目前上传仅支持新窗口使用，不支持挂件直接使用

**Comment by terwer** [comment]
我想了下，挂件版还是支持吧。新窗口和挂件都支持。请期待0.8.0版本。

**Comment by OpaqueGlass** [comment]
感谢大佬❤

**Comment by terwer** [comment]
已经开发完成，3.26发布0.8.0
